nelmio_api_doc:
    documentation:
        info:
            title: Opus test assignment
            description: This API allows to import a dictionary and search for anagrams.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
